language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update
  - composer validate

install:
  # gearman
  - sudo apt-get remove gearman-job-server
  - sudo apt-get install gearman-job-server libgearman-dev
  - printf "\n"| pecl install gearman-1.0.3
  ## Composer
  - composer install

script:
  - gearmand -d
  - phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
